[".zsh-syntax-highlighting"]
    type = "git-repo"
    url = "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
    [".zsh-syntax-highlighting".pull]
        args = ["--ff-only"]


[".zsh-completions"]
    type = "git-repo"
    url = "git clone https://github.com/zsh-users/zsh-completions.git"
    refreshPeriod = "168h"
    [".zsh-completions".pull]
        args = ["--ff-only"]
