#!/usr/bin/env zsh

# The following lines were added by compinstall
zstyle :compinstall filename '$XDG_CONFIG_HOME/zsh/.zshrc'
# keybindings set to vim
bindkey -v
# End of lines configured by zsh-newuser-install

#-----------------------$
# Load scripts
#-----------------------$

#----------------------------------------------------------------------------------------------------------@#
fpath=($ZDOTDIR/plugins/zsh-completions/src $fpath )                         #  Completions
autoload -Uz compinit; compinit
_comp_options+=(globdots)
source $ZDOTDIR/plugins/completion.zsh
#----------------------------------------------------------------------------------------------------------@#
fpath=($ZDOTDIR/plugins/Prompt $fpath )                                      # script defining prompt
autoload -Uz prompt_purification_setup && prompt_purification_setup
#----------------------------------------------------------------------------------------------------------@#
#!/bin/bashxrdb -merge -I$HOME $XDG_CONFIG_HOME/X11/Xresources                          # Xresources
#----------------------------------------------------------------------------------------------------------@#
fpath=($ZDOTDIR/Scripts $fpath )                                             # to run user installed scripts
autoload -Uz Scripts; Scripts
#----------------------------------------------------------------------------------------------------------@#
fpath=($ZDOTDIR/plugins $fpath )                                             # reverse of cd
autoload -Uz bd; bd


#-----------------------$
# Source files
#-----------------------$
source $ZDOTDIR/Aliases/aliases                                              # aliases
source $ZDOTDIR/env/env                                                      # zsh env config
source $ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh  # Highlight for terminal
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
source /home/phlight/.config/broot/launcher/bash/br

#-----------------------$
# Compiler makeflags
#-----------------------$
CORES=$(nproc)
LOAD=$((CORES/2))
JOBS=$((LOAD+1))
export MAKEFLAGS="-j$JOBS -l$LOAD"                                           # makeflag

eval "$(zoxide init zsh)"
